openapi: 3.0.0
info:
  title: fas-server
  version: 1.0.0
servers:
  - url: http://localhost:3003
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Health
  - name: Auth
  - name: Booking
paths:
  /ping:
    get:
      tags:
        - Health
      summary: Ping
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Sign-In
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@example.com
                password: admin
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/me:
    get:
      tags:
        - Auth
      summary: Current-User
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/booking:
    post:
      tags:
        - Booking
      summary: Add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                pickupLocation: China Town
                vanType: small
                deliveryTime: "2024-07-12T11:07:21.963+00:00"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Booking
      summary: Find
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/booking/669116ed38f59922288aa562:
    patch:
      tags:
        - Booking
      summary: Edit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                pickupLocation: Town BB
                vanType: small
                deliveryTime: "2024-07-12T11:07:21.963+00:00"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Booking
      summary: Show
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Booking
      summary: Delete
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
